allhosts:
  children:
    myservers:
      hosts:
        my-compute-instance:
          ansible_ssh_private_key_file: ~/.ssh/ansible_ssh_key
          ansible_host: my-instance
          zone: us-east1-d
      vars:
        ansible_user: cycy_menseau
    mydbs:
      hosts:
        my-postgres-instance:
          ansible_ssh_private_key_file: ~/.ssh/postgres_ssh_key
          ansible_host: my-postgres-instance
          zone: us-east1-d
      vars:
        ansible_user: cycy_menseau
